version: 1
formatters:
  simple:
    format: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file: 
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: 'dict_file.log'
  file_1:
    class : logging.handlers.RotatingFileHandler
    formatter: simple
    filename: rot.log
    maxBytes: 1024
    backupCount: 3
loggers:
  superscript:
    level: DEBUG
    handlers: [file_1]
    propagate: no
root:
  level: DEBUG
  handlers: [console,file]
